package com.scaleforge.core.service;

import com.scaleforge.core.model.ScalingDecision;
import lombok.extern.slf4j.Slf4j;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.stereotype.Service;
import jakarta.mail.internet.MimeMessage;

@Service
@Slf4j
public class EmailService {

    private final JavaMailSender mailSender;

    @Autowired
    public EmailService(@Autowired(required = false) JavaMailSender mailSender) {
        this.mailSender = mailSender;
    }

    // Dedicated logger for email dumps in case SMTP is not running
    private static final Logger mailLogger = LoggerFactory.getLogger("com.scaleforge.mail");

    public boolean sendScalingAlert(ScalingDecision decision) {
        String subject = "[ScaleForge Alert] Cluster Capacity Scale Event: " + decision.getAction();
        
        StringBuilder htmlBody = new StringBuilder();
        htmlBody.append("<html><body>");
        htmlBody.append("<h2>ScaleForge Capacity Action Notification</h2>");
        htmlBody.append("<hr/>");
        htmlBody.append("<p><strong>Action Taken:</strong> <span style='color:#d9534f; font-weight:bold;'>")
                .append(decision.getAction()).append("</span></p>");
        htmlBody.append("<p><strong>Reason:</strong> ").append(decision.getDecisionReason()).append("</p>");
        htmlBody.append("<p><strong>Idempotency Key:</strong> <code>").append(decision.getIdempotencyKey()).append("</code></p>");
        htmlBody.append("<p><strong>Cluster Targets:</strong> Replicas=").append(decision.getTargetReplicas())
                .append(" | Nodes=").append(decision.getTargetNodes()).append("</p>");
        htmlBody.append("<p><strong>Timestamp:</strong> ").append(decision.getTimestamp()).append("</p>");
        htmlBody.append("<hr/>");
        htmlBody.append("<p style='font-size:11px; color:#888;'>This is an automated notification generated by ScaleForge Autonomous Controller.</p>");
        htmlBody.append("</body></html>");

        if (mailSender != null) {
            try {
                MimeMessage message = mailSender.createMimeMessage();
                MimeMessageHelper helper = new MimeMessageHelper(message, true, "UTF-8");
                helper.setTo("admin@scaleforge.local");
                helper.setFrom("alerts@scaleforge.local");
                helper.setSubject(subject);
                helper.setText(htmlBody.toString(), true);
                
                mailSender.send(message);
                log.info("Scaling alert email sent successfully to admin@scaleforge.local.");
                return true;
            } catch (Exception e) {
                log.debug("SMTP server not reachable. Falling back to console notification dump. Cause: {}", e.getMessage());
            }
        }

        // Fallback logging dump for developer sandbox visual verification
        mailLogger.info("\n" +
                "================================================================================\n" +
                "ALERT EMAIL DUMP (SMTP Fallback)\n" +
                "Subject: {}\n" +
                "--------------------------------------------------------------------------------\n" +
                "Action   : {}\n" +
                "Reason   : {}\n" +
                "Token    : {}\n" +
                "Targets  : Replicas={} | Nodes={}\n" +
                "Time     : {}\n" +
                "================================================================================",
                subject,
                decision.getAction(),
                decision.getDecisionReason(),
                decision.getIdempotencyKey(),
                decision.getTargetReplicas(),
                decision.getTargetNodes(),
                decision.getTimestamp());
        return false;
    }
}
